# Generated by Django 6.0.5 on 2026-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemsettings_auto_approve_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('auth', 'Auth'), ('page_view', 'Page view'), ('feature_exec', 'Feature exec')], db_index=True, default='auth', max_length=16),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('otp_request', 'OTP request'), ('otp_verify', 'OTP verify'), ('admin_approve', 'Admin approve'), ('admin_reject', 'Admin reject'), ('registration', 'Registration'), ('email_sent', 'Email sent'), ('activity', 'Activity')], db_index=True, max_length=32),
        ),
    ]
