# Generated by Django 6.0.4 on 2026-05-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_add_ticket_number_column_db_only'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookConfig',
        ),
    ]
