# Generated by Django 6.0.4 on 2026-05-26 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0014_alert_dashboard_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='alerts_alert_ts_brin',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alerts_alert_src_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alerts_alert_rule_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alerts_alert_sev_idx',
        ),
        migrations.RemoveIndex(
            model_name='alert',
            name='alerts_alert_cat_idx',
        ),
    ]
