# Generated by Django 6.0.5 on 2026-09-21 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_prefect_deployment_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowschedule',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workflowschedule',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowschedule',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='workflowschedule',
            name='synced_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkflowRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('manifest', models.JSONField()),
                ('published_at', models.DateTimeField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['workflow', 'version'],
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='published_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.workflowrevision'),
        ),
        migrations.AddConstraint(
            model_name='workflowrevision',
            constraint=models.UniqueConstraint(fields=('workflow', 'version'), name='uniq_workflow_revision'),
        ),
        migrations.AddConstraint(
            model_name='workflowrevision',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='workflow_revision_positive_version'),
        ),
    ]
