# Generated by Django 6.0.5 on 2026-08-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_add_field_aliases'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notableevent',
            new_name='risk_notabl_status_dcbc21_idx',
            old_name='risk_notable_status_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='notableevent',
            new_name='risk_notabl_risk_ob_9d2e72_idx',
            old_name='risk_notable_obj_status_idx',
        ),
        migrations.RenameIndex(
            model_name='riskevent',
            new_name='risk_event_profile_116c70_idx',
            old_name='risk_event_profile_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='riskevent',
            new_name='risk_event_alert_i_115e89_idx',
            old_name='risk_event_alert_id_idx',
        ),
        migrations.RenameIndex(
            model_name='riskobjectprofile',
            new_name='risk_object_current_6d6ba4_idx',
            old_name='risk_object__current_score_idx',
        ),
        migrations.RenameIndex(
            model_name='riskobjectprofile',
            new_name='risk_object_status_5d9c4a_idx',
            old_name='risk_object__status_score_idx',
        ),
        migrations.RenameIndex(
            model_name='riskscoreentry',
            new_name='risk_score__profile_ee9eeb_idx',
            old_name='risk_score_entry_profile_ts_idx',
        ),
        migrations.AlterField(
            model_name='globalriskconfig',
            name='field_aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='riskruleconfig',
            name='field_aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
