# Generated by Django 6.0.5 on 2026-08-31 05:50

from django.db import migrations, models


def dedupe_risk_events(apps, schema_editor):
    """Keep the earliest RiskEvent per (alert_id, profile); delete the rest so
    the unique constraint can be created on existing data."""
    RiskEvent = apps.get_model('risk', 'RiskEvent')
    seen = set()
    dup_ids = []
    for pk, alert_id, profile_id in (
        RiskEvent.objects.order_by('id').values_list('id', 'alert_id', 'profile_id')
    ):
        key = (alert_id, profile_id)
        if key in seen:
            dup_ids.append(pk)
        else:
            seen.add(key)
    if dup_ids:
        RiskEvent.objects.filter(id__in=dup_ids).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_rename_risk_notable_status_ts_idx_risk_notabl_status_dcbc21_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_risk_events, noop_reverse),
        migrations.AddConstraint(
            model_name='riskevent',
            constraint=models.UniqueConstraint(fields=('alert_id', 'profile'), name='uniq_riskevent_alert_profile'),
        ),
    ]
