# Generated by Django 6.0.4 on 2026-05-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='localdetectionruleversion',
            new_name='detection_r_rule_id_497afd_idx',
            old_name='detection_r_rule_id_7f47b6_idx',
        ),
    ]
