# Generated by Django 6.0.4 on 2026-06-23 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0008_mitre_attack_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDetectionRuleMitreAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tactic_id', models.CharField(db_index=True, max_length=32)),
                ('tactic_name', models.CharField(max_length=128)),
                ('technique_id', models.CharField(db_index=True, max_length=32)),
                ('technique_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'detection_rule_mitre_attack',
            },
        ),
        migrations.RenameIndex(
            model_name='mitreattacktechniquetactic',
            new_name='mitre_attac_techniq_b948d4_idx',
            old_name='mitre_attac_techniq_b85d1d_idx',
        ),
        migrations.RenameIndex(
            model_name='mitreattacktechniquetactic',
            new_name='mitre_attac_tactic__11e9a8_idx',
            old_name='mitre_attac_tactic__77b941_idx',
        ),
        migrations.AddField(
            model_name='localdetectionrulemitreattack',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitre_attack_mappings', to='detections.localdetectionrule'),
        ),
        migrations.AddIndex(
            model_name='localdetectionrulemitreattack',
            index=models.Index(fields=['rule', 'tactic_id'], name='detection_r_rule_id_031214_idx'),
        ),
        migrations.AddIndex(
            model_name='localdetectionrulemitreattack',
            index=models.Index(fields=['tactic_id', 'technique_id'], name='detection_r_tactic__b92baa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='localdetectionrulemitreattack',
            unique_together={('rule', 'tactic_id', 'technique_id')},
        ),
    ]
