# Generated by Codex on 2026-06-23

from django.db import migrations, models


def copy_sigma_rule_id_from_fk(apps, schema_editor):
    LocalDetectionRuleMitreAttack = apps.get_model("detections", "LocalDetectionRuleMitreAttack")

    for row in LocalDetectionRuleMitreAttack.objects.select_related("rule").all().iterator():
        sigma_rule_id = ""
        rule = getattr(row, "rule", None)
        if rule is not None:
            sigma_rule_id = str(getattr(rule, "rule_uuid", "") or "").strip()
        if sigma_rule_id:
            row.sigma_rule_id = sigma_rule_id
            row.save(update_fields=["sigma_rule_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("detections", "0009_localdetectionrulemitreattack_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localdetectionrulemitreattack",
            name="sigma_rule_id",
            field=models.CharField(blank=True, db_column="sigma_rule_id", default="", max_length=128),
        ),
        migrations.AddField(
            model_name="localdetectionrulemitreattack",
            name="kibana_rule_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.RunPython(copy_sigma_rule_id_from_fk, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="localdetectionrulemitreattack",
            unique_together=set(),
        ),
        migrations.RemoveIndex(
            model_name="localdetectionrulemitreattack",
            name="detection_r_rule_id_031214_idx",
        ),
        migrations.RemoveField(
            model_name="localdetectionrulemitreattack",
            name="rule",
        ),
        migrations.RenameField(
            model_name="localdetectionrulemitreattack",
            old_name="sigma_rule_id",
            new_name="rule_id",
        ),
        migrations.AlterField(
            model_name="localdetectionrulemitreattack",
            name="rule_id",
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name="localdetectionrulemitreattack",
            index=models.Index(fields=["rule_id", "tactic_id"], name="detection_r_rule_id_031214_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="localdetectionrulemitreattack",
            unique_together={("rule_id", "tactic_id", "technique_id")},
        ),
    ]
