import React from "react";
import { Button, Card, Input, InputNumber, Popconfirm, Radio, Select, Space, Tag, Typography } from "antd";

import type { DetectionRuleDetail } from "services/detections";
import {
  applyIndexPatternsToEsql,
  defaultRiskEntityField,
  parseIndexPatterns,
  resolveAlertModeConnector,
  RISK_ENTITY_FIELD_OPTIONS,
  type AlertMode,
  type RiskEntityConfig,
  type RiskEntityType,
} from "./utils";

type ConnectorRow = { id: string; name: string; connector_type_id?: string };
type KibanaMetadata = { published?: boolean; remote_id?: string; rule_id?: string; enabled?: boolean; name?: string; updated_at?: string };

type Props = {
  detail: DetectionRuleDetail;
  detailTab: "sigma" | "esql" | "version";
  versions: any[];
  connectors: ConnectorRow[];
  resolvedElasticActionsText: string;
  resolvedElasticActionsError?: string;
  elasticIndexPatternsText: string;
  esqlText: string;
  esqlSource: "autogenerated" | "manual";
  riskEntities: RiskEntityConfig[];
  scheduleInterval: string;
  scheduleFrom: string;
  kibanaMetadata: KibanaMetadata;
  rulePreviewLoading: boolean;
  onBack: () => void;
  onEdit: () => void;
  onPreview: () => Promise<void>;
  onPublish: () => Promise<void>;
  onSetDetailTab: (value: "sigma" | "esql" | "version") => void;
  onRollbackVersion: (version: number) => Promise<void>;
  onSaveAlertMode: () => Promise<void>;
  onSaveSchedule: () => Promise<void>;
  onSyncKibanaEnabled: (enabled: boolean) => Promise<void>;
  onDeleteKibanaRule: () => Promise<void>;
  onLoadConnectors: () => Promise<void>;
  onSaveEsql: () => Promise<void>;
  onRegenerateEsqlFromSigma: () => Promise<void>;
  onSetElasticIndexPatternsText: (value: string) => void;
  onSetEsqlText: (value: string) => void;
  onSetRiskEntities: (value: RiskEntityConfig[]) => void;
  onSetScheduleInterval: (value: string) => void;
  onSetScheduleFrom: (value: string) => void;
};

export default function DetectionRuleDetail(props: Props) {
  const meta = props.detail.meta || {};
  const compiled = props.detail.compiled || {};
  const logSourceParts = [meta.product, meta.service, meta.category].filter((value) => String(value || "").trim());
  const compiledLanguage = String(compiled.language || (compiled.lucene ? "lucene" : "esql")).toLowerCase();
  const queryLabel = compiledLanguage === "lucene" ? "Lucene" : "ES|QL";
  const esqlSource = props.esqlSource || "autogenerated";
  const queryPreview =
    compiledLanguage === "lucene"
      ? String(compiled.lucene || "*")
      : applyIndexPatternsToEsql(props.esqlText || compiled.esql || "*", parseIndexPatterns(props.elasticIndexPatternsText));
  const riskConnector = resolveAlertModeConnector(props.connectors, "risk");
  const notableConnector = resolveAlertModeConnector(props.connectors, "notable");
  const entityRiskActive = props.riskEntities.length > 0;
  const needsNotableConnector = props.riskEntities.some((entity) => entity.output === "notable");
  const updateEntity = (index: number, patch: Partial<RiskEntityConfig>) => {
    props.onSetRiskEntities(props.riskEntities.map((entity, entityIndex) => entityIndex === index ? { ...entity, ...patch } : entity));
  };
  const [selectedVersion, setSelectedVersion] = React.useState<number | undefined>(undefined);
  const formatVersionTime = (value: any) => {
    const raw = String(value || "").trim();
    if (!raw) return "";
    const date = new Date(raw);
    if (Number.isNaN(date.getTime())) return raw;
    const pad = (num: number) => String(num).padStart(2, "0");
    return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`;
  };
  const rollbackOptions = props.versions.map((item) => ({
    value: Number(item.version),
    label: `v${item.version} ${item.change_type || "update"} ${formatVersionTime(item.created_at)}`,
  }));
  const selectedVersionDetails =
    props.versions.find((item) => Number(item.version) === Number(selectedVersion)) ||
    props.versions[0] ||
    null;
  React.useEffect(() => {
    if (!selectedVersionDetails && props.versions.length) {
      setSelectedVersion(Number(props.versions[0].version));
      return;
    }
    if (!selectedVersion && props.versions.length) {
      setSelectedVersion(Number(props.versions[0].version));
    }
  }, [props.versions, selectedVersion, selectedVersionDetails]);
  const tabText =
    props.detailTab === "sigma"
      ? meta.detection_preview || props.detail.yaml || ""
      : props.detailTab === "esql"
        ? queryPreview
        : "";

  return (
    <Card>
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 14 }}>
        <Button onClick={props.onBack}>Back to List</Button>
        <Space>
          <Button onClick={props.onEdit}>Edit</Button>
          <Button loading={props.rulePreviewLoading} onClick={props.onPreview}>Preview in Kibana</Button>
          <Button type="primary" onClick={props.onPublish}>Publish to Kibana</Button>
        </Space>
      </div>

      <Typography.Title level={2} style={{ marginTop: 0 }}>{meta.title || props.detail.id}</Typography.Title>
      <Space style={{ marginBottom: 10 }}>
        <Tag color="red">{meta.level || "medium"}</Tag>
        <Tag color="orange">{meta.status || "draft"}</Tag>
        <Typography.Text type="secondary">v{props.detail.version || 1}</Typography.Text>
      </Space>
      <Typography.Paragraph type="secondary">{meta.description || "No description"}</Typography.Paragraph>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10, marginBottom: 16 }}>
        <Card size="small" title="Log Source">{logSourceParts.length ? logSourceParts.join(" / ") : "unknown"}</Card>
        <Card size="small" title="Mapping Profile">{meta.profile || (compiled.profiles || [])[0] || "-"}</Card>
        <Card size="small" title="Tags">{Array.isArray(meta.tags) && meta.tags.length ? meta.tags.join(", ") : "-"}</Card>
      </div>

      <Card
        size="small"
        title="Kibana Detection Rule"
        style={{ marginBottom: 16 }}
        extra={
          props.kibanaMetadata.published ? (
            <Tag color={props.kibanaMetadata.enabled ? "green" : "gold"}>{props.kibanaMetadata.enabled ? "Enabled" : "Published but Disabled"}</Tag>
          ) : (
            <Tag>Not Published</Tag>
          )
        }
      >
        <Space wrap>
          <Typography.Text type="secondary">Sigma Rule ID: {props.kibanaMetadata.rule_id || "-"}</Typography.Text>
          <Typography.Text type="secondary">Kibana Rule ID: {props.kibanaMetadata.remote_id || "-"}</Typography.Text>
          <Button size="small" loading={props.rulePreviewLoading} onClick={props.onPreview}>Rule Preview</Button>
          <Button size="small" disabled={!props.kibanaMetadata.published || Boolean(props.kibanaMetadata.enabled)} onClick={() => props.onSyncKibanaEnabled(true)}>Enable</Button>
          <Button size="small" disabled={!props.kibanaMetadata.published || !Boolean(props.kibanaMetadata.enabled)} onClick={() => props.onSyncKibanaEnabled(false)}>Disable</Button>
          <Popconfirm title="Delete the detection rule from Kibana?" okText="Delete" cancelText="Cancel" onConfirm={props.onDeleteKibanaRule}>
            <Button size="small" danger disabled={!props.kibanaMetadata.published}>Delete Kibana Rule</Button>
          </Popconfirm>
        </Space>
      </Card>

      <Card
        size="small"
        title="Cron Job / Schedule"
        style={{ marginBottom: 16 }}
        extra={<Button size="small" onClick={props.onSaveSchedule}>Save</Button>}
      >
        <Typography.Paragraph type="secondary" style={{ marginTop: 0 }}>
          Configure how often Kibana executes this detection and how far back each run searches. Kibana Detection uses interval scheduling instead of a five-field cron expression.
        </Typography.Paragraph>
        <Space wrap align="end">
          <Space direction="vertical" size={4}>
            <Typography.Text strong>Run every</Typography.Text>
            <Select
              value={props.scheduleInterval}
              onChange={props.onSetScheduleInterval}
              style={{ width: 180 }}
              options={["1m", "5m", "10m", "15m", "30m", "1h"].map((value) => ({ value, label: value }))}
            />
          </Space>
          <Space direction="vertical" size={4}>
            <Typography.Text strong>Lookback</Typography.Text>
            <Input
              value={props.scheduleFrom}
              onChange={(event) => props.onSetScheduleFrom(event.target.value)}
              placeholder="now-16m"
              style={{ width: 180 }}
            />
          </Space>
          <Typography.Text type="secondary">Recommended: run every 1m with a lookback slightly longer than the 15m risk window.</Typography.Text>
        </Space>
      </Card>

      <Card
        size="small"
        title="Entity Risk"
        style={{ marginBottom: 16 }}
        extra={<Button size="small" onClick={props.onSaveAlertMode}>Save</Button>}
      >
        <Typography.Paragraph type="secondary" style={{ marginTop: 0 }}>
          Map alert fields to risk entities. Notable event always creates the corresponding risk event as well.
        </Typography.Paragraph>
        <div style={{ overflowX: "auto" }}>
          <div style={{ minWidth: 820 }}>
            <div style={{ display: "grid", gridTemplateColumns: "150px minmax(220px, 1fr) 130px 300px 80px", gap: 12, padding: "10px 12px", background: "#f5f7fa", borderRadius: "6px 6px 0 0" }}>
              <Typography.Text strong>Entity type</Typography.Text>
              <Typography.Text strong>Entity field</Typography.Text>
              <Typography.Text strong>Risk score</Typography.Text>
              <Typography.Text strong>Output</Typography.Text>
              <Typography.Text strong>Actions</Typography.Text>
            </div>
            {props.riskEntities.map((entity, index) => (
              <div key={`${index}-${entity.entity_type}`} style={{ display: "grid", gridTemplateColumns: "150px minmax(220px, 1fr) 130px 300px 80px", gap: 12, alignItems: "center", padding: "12px", border: "1px solid #f0f0f0", borderTop: 0 }}>
                <Select
                  value={entity.entity_type}
                  onChange={(value) => {
                    const nextType = value as RiskEntityType;
                    updateEntity(index, { entity_type: nextType, entity_field: defaultRiskEntityField(nextType) });
                  }}
                  options={[
                    { value: "host", label: "Host" },
                    { value: "user", label: "User" },
                    { value: "ip", label: "IP Address" },
                    { value: "service", label: "Service" },
                    { value: "risk_object", label: "Risk Object" },
                  ]}
                />
                <Select
                  showSearch
                  value={entity.entity_field}
                  onChange={(value) => updateEntity(index, { entity_field: value })}
                  options={RISK_ENTITY_FIELD_OPTIONS[entity.entity_type].map((field) => ({ value: field, label: field }))}
                />
                <InputNumber min={0} max={100} value={entity.risk_score} onChange={(value) => updateEntity(index, { risk_score: Number(value ?? 0) })} style={{ width: "100%" }} />
                <Radio.Group value={entity.output} onChange={(event) => updateEntity(index, { output: event.target.value as AlertMode })} buttonStyle="solid">
                  <Radio.Button value="risk">Risk event</Radio.Button>
                  <Radio.Button value="notable">Notable event</Radio.Button>
                </Radio.Group>
                <Button danger size="small" onClick={() => props.onSetRiskEntities(props.riskEntities.filter((_, entityIndex) => entityIndex !== index))}>Remove</Button>
              </div>
            ))}
            {!props.riskEntities.length ? (
              <div style={{ padding: "18px 12px", border: "1px solid #f0f0f0", borderTop: 0 }}>
                <Typography.Text type="secondary">Entity Risk is not configured for this detection rule.</Typography.Text>
              </div>
            ) : null}
          </div>
        </div>
        <Button
          style={{ marginTop: 12 }}
          onClick={() => props.onSetRiskEntities([...props.riskEntities, { entity_type: "host", entity_field: "host.name", risk_score: 50, output: "risk" }])}
        >
          + Add entity
        </Button>
        <Space wrap style={{ marginTop: 12, display: "flex" }}>
          {!entityRiskActive ? <Tag>Entity Risk disabled</Tag> : null}
          {entityRiskActive ? <Typography.Text type="secondary">Risk index</Typography.Text> : null}
          {entityRiskActive ? (riskConnector ? <Tag color="green">{riskConnector.name}</Tag> : <Tag color="red">Risk .index connector not configured</Tag>) : null}
          {needsNotableConnector ? <Typography.Text type="secondary">Notable index</Typography.Text> : null}
          {needsNotableConnector ? (notableConnector ? <Tag color="green">{notableConnector.name}</Tag> : <Tag color="red">Notable .index connector not configured</Tag>) : null}
        </Space>
      </Card>

      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 8 }}>
        <Typography.Title level={3} style={{ margin: 0 }}>Detection</Typography.Title>
        <Typography.Text type="secondary">{meta.detection_preview ? "Detection fields ready" : "0 detection fields"}</Typography.Text>
      </div>

      <Space style={{ marginBottom: 10 }}>
        <Button type={props.detailTab === "sigma" ? "primary" : "default"} onClick={() => props.onSetDetailTab("sigma")}>Sigma</Button>
        <Button type={props.detailTab === "esql" ? "primary" : "default"} onClick={() => props.onSetDetailTab("esql")}>{queryLabel}</Button>
        <Button type={props.detailTab === "version" ? "primary" : "default"} onClick={() => props.onSetDetailTab("version")}>Versions</Button>
      </Space>

      {compiled.error ? (
        <Card size="small" style={{ marginBottom: 12 }}>
          <Typography.Text type={compiledLanguage === "lucene" ? "warning" : "danger"}>
            {compiledLanguage === "lucene" ? `ES|QL compile failed, using Lucene fallback: ${compiled.error}` : compiled.error}
          </Typography.Text>
        </Card>
      ) : null}

      {props.detailTab === "version" ? (
        <Space wrap style={{ marginBottom: 10 }}>
          <Select
            placeholder="Select a version"
            value={selectedVersion}
            onChange={(value) => setSelectedVersion(Number(value))}
            style={{ width: 320 }}
            options={rollbackOptions}
          />
          <Button
            size="small"
            disabled={!selectedVersion}
            onClick={() => {
              if (!selectedVersion) return;
              props.onRollbackVersion(selectedVersion);
            }}
          >
            Roll Back Selected Version
          </Button>
        </Space>
      ) : null}

      {props.detailTab === "version" && selectedVersionDetails ? (
        <Card
          size="small"
          style={{ marginBottom: 12 }}
          title={`v${selectedVersionDetails.version} ${selectedVersionDetails.change_type || "update"}`}
        >
          <Space direction="vertical" style={{ width: "100%" }} size={8}>
            <Typography.Text type="secondary">
              {formatVersionTime(selectedVersionDetails.created_at)} by {selectedVersionDetails.changed_by || "unknown"}
            </Typography.Text>
            {Array.isArray(selectedVersionDetails.change_summary) && selectedVersionDetails.change_summary.length ? (
              selectedVersionDetails.change_summary.map((row: any, index: number) => (
                <Card key={`${selectedVersionDetails.version}-${index}`} size="small">
                  <Typography.Text strong>{String(row?.label || row?.field || "Changed")}</Typography.Text>
                  <div>{String(row?.message || "Changed")}</div>
                  {row?.before ? <Typography.Text type="secondary">Before: {String(row.before)}</Typography.Text> : null}
                  {row?.after ? <div><Typography.Text type="secondary">After: {String(row.after)}</Typography.Text></div> : null}
                  {row?.diff ? (
                    <pre style={{ marginTop: 8, background: "#0c1733", color: "#e8eefc", borderRadius: 8, padding: 12, overflow: "auto", whiteSpace: "pre-wrap" }}>
                      {String(row.diff)}
                    </pre>
                  ) : null}
                </Card>
              ))
            ) : (
              <Typography.Text type="secondary">No detailed change summary recorded for this version.</Typography.Text>
            )}
          </Space>
        </Card>
      ) : null}

      {props.detailTab === "esql" ? (
        <div style={{ display: "grid", gridTemplateColumns: "minmax(0, 1.2fr) minmax(320px, 0.8fr)", gap: 16 }}>
          <Space direction="vertical" style={{ width: "100%" }} size={16}>
            <Card
              size="small"
              title={`${queryLabel} Query`}
              extra={
                <Space>
                  <Tag color={esqlSource === "manual" ? "blue" : "green"}>
                    {esqlSource === "manual" ? "manual" : "autogenerated"}
                  </Tag>
                  <Button size="small" onClick={props.onRegenerateEsqlFromSigma}>Regenerate from Sigma</Button>
                  {compiledLanguage === "esql" ? <Button size="small" type="primary" onClick={props.onSaveEsql}>Save ES|QL</Button> : null}
                </Space>
              }
            >
              <Space direction="vertical" style={{ width: "100%" }} size={10}>
                <Typography.Text type="secondary">
                  Index patterns belong to the Elastic detection rule itself and will be submitted as the detection rule `index` field.
                </Typography.Text>
                <Input.TextArea
                  value={props.elasticIndexPatternsText}
                  onChange={(e) => props.onSetElasticIndexPatternsText(e.target.value)}
                  rows={4}
                  placeholder={"logs-*\nwinlogbeat-*"}
                />
                <Typography.Text type="secondary">
                  Modify the ES|QL below and save it to mark this rule as manual. Publishing uses this saved query.
                </Typography.Text>
                <Input.TextArea
                  value={compiledLanguage === "esql" ? props.esqlText : tabText}
                  onChange={(event) => props.onSetEsqlText(event.target.value)}
                  readOnly={compiledLanguage !== "esql"}
                  rows={14}
                  style={{ fontFamily: "Consolas, 'Courier New', monospace" }}
                />
              </Space>
            </Card>
          </Space>
          <Card size="small" title="Kibana Detection Actions" extra={<Button size="small" onClick={props.onLoadConnectors}>Refresh Connectors</Button>}>
            <Space direction="vertical" style={{ width: "100%" }} size={10}>
              <Typography.Text type="secondary">
                Risk/Notable index actions are generated from Entity Risk. The preview below is the exact action list used when publishing.
              </Typography.Text>
              {props.resolvedElasticActionsError ? <Typography.Text type="danger">{props.resolvedElasticActionsError}</Typography.Text> : null}
              <Typography.Text strong>Generated action preview</Typography.Text>
              <Input.TextArea value={props.resolvedElasticActionsText} readOnly rows={16} />
            </Space>
          </Card>
        </div>
      ) : props.detailTab !== "version" ? (
        <pre style={{ margin: 0, background: "#0c1733", color: "#e8eefc", borderRadius: 8, padding: 16, minHeight: 220, overflow: "auto", whiteSpace: "pre-wrap" }}>
          {tabText}
        </pre>
      ) : null}
    </Card>
  );
}
