"use client";

import React, { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { App, Button, Card, Collapse, Input, Modal, Space, Statistic, Table, Tabs, Typography } from "antd";

import {
  createDetectionDeployment,
  createDetectionMapping,
  createPublishedDetectionRule,
  deleteDetectionRule,
  deleteDetectionMappings,
  deletePublishedDetectionRule,
  exportDetectionMappings,
  exportDetectionRules,
  compileDetectionRule,
  getDetectionRule,
  getPublishedDetectionRule,
  getPublishedRuleVersions,
  listDetectionDeployments,
  listDetectionMappings,
  listPublishedConnectors,
  listDetectionRules,
  patchPublishedDetectionRule,
  previewPublishedDetectionRule,
  rollbackPublishedRuleVersion,
  saveDetectionRule,
  updatePublishedDetectionRule,
  uploadDetectionMappings,
  uploadDetectionRules,
  type DetectionDeploymentRecord,
  type DetectionRuleDetail,
  type DetectionRuleItem,
} from "services/detections";

import DetectionDeployments from "./DetectionDeployments";
import DetectionMappings from "./DetectionMappings";
import DetectionRuleDetailView from "./DetectionRuleDetail";
import DetectionRuleList from "./DetectionRuleList";
import {
  applyIndexPatternsToEsql,
  formatJson,
  guessElasticIndexPatternsFromProfile,
  parseIndexPatterns,
  routeElasticActionsByAlertMode,
  type RiskEntityConfig,
} from "./utils";

type RuleRow = DetectionRuleItem & {
  level?: string;
  status?: string;
  logsource?: string;
  profile?: string;
  tags?: string[];
  publish_status?: string;
  kibana_enabled?: boolean;
  kibana_rule_id?: string;
};

type LocalMapRow = { id: string | number; sigma: string; splunk: string; elastic: string; elastic_is_multivalue?: boolean; elastic_index_patterns?: string[]; mapping_profile?: string };
type ConnectorRow = { id: string; name: string; connector_type_id?: string };
type KibanaMetadata = { published?: boolean; remote_id?: string; rule_id?: string; enabled?: boolean; name?: string; updated_at?: string };
type MappingDraft = {
  mapping_profile: string;
  sigma: string;
  splunk: string;
  elastic: string;
  elastic_is_multivalue: boolean;
  elastic_index_patterns: string;
  category: string;
  data_source: string;
  event_category: string;
};

const normalizeRiskEntities = (value: unknown): RiskEntityConfig[] => {
  if (!Array.isArray(value)) return [];
  return value
    .filter((entity): entity is Partial<RiskEntityConfig> => Boolean(entity) && typeof entity === "object")
    .map((entity) => ({
      entity_type: (entity.entity_type || "host") as RiskEntityConfig["entity_type"],
      entity_field: String(entity.entity_field || "host.name"),
      risk_score: Number.isFinite(Number(entity.risk_score)) ? Number(entity.risk_score) : 50,
      output: (entity.output === "notable" ? "notable" : "risk") as RiskEntityConfig["output"],
    }))
    .filter((entity) => entity.entity_field.trim());
};

export default function Detections({ initialRuleId }: { initialRuleId?: string } = {}) {
  const { message } = App.useApp();
  const router = useRouter();
  const DETECTION_BASE = "/settings/detection";

  const [topTab, setTopTab] = useState("rules");
  const [rules, setRules] = useState<RuleRow[]>([]);
  const [loading, setLoading] = useState(false);
  const [search, setSearch] = useState("");
  const [productFilter, setProductFilter] = useState<string>("all");
  const [severityFilter, setSeverityFilter] = useState<string>("all");
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [selectedRuleIds, setSelectedRuleIds] = useState<React.Key[]>([]);

  const [selectedId, setSelectedId] = useState("");
  const [detail, setDetail] = useState<DetectionRuleDetail | null>(null);
  const [versions, setVersions] = useState<any[]>([]);
  const [detailTab, setDetailTab] = useState<"sigma" | "esql" | "version">("sigma");

  const [editorOpen, setEditorOpen] = useState(false);
  const [editorId, setEditorId] = useState("");
  const [editorYaml, setEditorYaml] = useState("");
  const [elasticIndexPatternsText, setElasticIndexPatternsText] = useState("");
  const [esqlText, setEsqlText] = useState("");
  const [esqlSource, setEsqlSource] = useState<"autogenerated" | "manual">("autogenerated");
  const [riskEntities, setRiskEntities] = useState<RiskEntityConfig[]>([]);
  const [scheduleInterval, setScheduleInterval] = useState("1m");
  const [scheduleFrom, setScheduleFrom] = useState("now-16m");
  const [connectors, setConnectors] = useState<ConnectorRow[]>([]);
  const [kibanaMetadata, setKibanaMetadata] = useState<KibanaMetadata>({});
  const [rulePreviewOpen, setRulePreviewOpen] = useState(false);
  const [rulePreviewLoading, setRulePreviewLoading] = useState(false);
  const [rulePreviewResult, setRulePreviewResult] = useState<any>(null);

  const [maps, setMaps] = useState<LocalMapRow[]>([]);
  const [selectedMappingIds, setSelectedMappingIds] = useState<React.Key[]>([]);
  const [mappingModalOpen, setMappingModalOpen] = useState(false);
  const [editingMappingId, setEditingMappingId] = useState<string | number | null>(null);
  const [mappingDraft, setMappingDraft] = useState<MappingDraft>({
    mapping_profile: "",
    sigma: "",
    splunk: "",
    elastic: "",
    elastic_is_multivalue: false,
    elastic_index_patterns: "",
    category: "",
    data_source: "",
    event_category: "",
  });
  const [deployments, setDeployments] = useState<DetectionDeploymentRecord[]>([]);
  const [githubUrl, setGithubUrl] = useState("");
  const [uploading, setUploading] = useState(false);
  const [mappingUploading, setMappingUploading] = useState(false);

  const downloadJson = (fileName: string, data: any) => {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  const downloadBlob = (fileName: string, blob: Blob) => {
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
  };

  const downloadText = (fileName: string, text: string, contentType: string) => {
    downloadBlob(fileName, new Blob([text], { type: contentType }));
  };

  const loadRules = async () => {
    setLoading(true);
    try {
      const list = await listDetectionRules();
      setRules(Array.isArray(list) ? (list as RuleRow[]) : []);
    } catch (e: any) {
      message.error(e?.response?.data?.detail || "Failed to load rules");
    } finally {
      setLoading(false);
    }
  };

  const loadMappings = async () => {
    try {
      const list = await listDetectionMappings();
      setMaps(
        (Array.isArray(list) ? list : []).map((row: any) => ({
          id: row.id,
          sigma: String(row.sigma || ""),
          splunk: String(row.splunk || ""),
          elastic: String(row.elastic || ""),
          elastic_is_multivalue: Boolean(row.elastic_is_multivalue),
          elastic_index_patterns: Array.isArray(row.elastic_index_patterns) ? row.elastic_index_patterns.map((item: any) => String(item || "").trim()).filter(Boolean) : [],
          mapping_profile: String(row.mapping_profile || ""),
          category: String(row.category || ""),
          data_source: String(row.data_source || ""),
          event_category: String(row.event_category || ""),
        })),
      );
    } catch (e: any) {
      message.error(e?.response?.data?.detail || "Failed to load mappings");
      setMaps([]);
    }
  };

  const loadDeployments = async () => {
    try {
      setDeployments(await listDetectionDeployments());
    } catch (e: any) {
      message.error(e?.response?.data?.detail || "Failed to load deployment records");
      setDeployments([]);
    }
  };

  const loadConnectors = async () => {
    try {
      const rows = await listPublishedConnectors();
      setConnectors(Array.isArray(rows) ? rows : []);
    } catch {
      setConnectors([]);
    }
  };

  const loadDetail = async (id: string) => {
    const nextDetail = await getDetectionRule(id);
    const indexPatterns =
      Array.isArray(nextDetail?.compiled?.elastic_index_patterns) && nextDetail.compiled.elastic_index_patterns.length
        ? nextDetail.compiled.elastic_index_patterns
        : Array.isArray(nextDetail?.payload?.elastic_index_patterns) && nextDetail.payload?.elastic_index_patterns.length
          ? nextDetail.payload.elastic_index_patterns
          : [];

    setSelectedId(id);
    setDetail(nextDetail);
    setElasticIndexPatternsText(indexPatterns.join("\n"));
    setEsqlText(String(nextDetail?.compiled?.esql || nextDetail?.payload?.esql || "*"));
    setEsqlSource(nextDetail?.compiled?.esql_source === "manual" || nextDetail?.payload?.esql_source === "manual" ? "manual" : "autogenerated");
    const rulePayload = nextDetail?.payload || {};
    const storedEntities = normalizeRiskEntities(rulePayload.risk_entities);
    const legacyLooksConfigured = rulePayload.entity_risk_enabled === undefined && storedEntities.some((entity: any) => (
      String(entity?.entity_type || "") !== "host"
      || String(entity?.entity_field || "") !== "host.name"
      || Number(entity?.risk_score ?? 50) !== 50
      || String(entity?.output || "") !== "notable"
    ));
    setRiskEntities(rulePayload.entity_risk_enabled === false && !legacyLooksConfigured ? [] : storedEntities);
    setScheduleInterval(String(rulePayload.schedule_interval || rulePayload.interval || "1m"));
    setScheduleFrom(String(rulePayload.schedule_from || rulePayload.from || "now-16m"));
    setKibanaMetadata(
      nextDetail?.payload?.kibana_metadata && typeof nextDetail.payload.kibana_metadata === "object"
        ? nextDetail.payload.kibana_metadata
        : {},
    );
    try {
      const publishedVersions = await getPublishedRuleVersions(id);
      setVersions(Array.isArray(publishedVersions?.data) ? publishedVersions.data : []);
    } catch {
      setVersions([]);
    }
  };

  useEffect(() => {
    loadRules();
    loadMappings();
    loadDeployments();
    loadConnectors();
  }, []);

  // Deep link from other modules (e.g. the Alerts "Detection Rule" quick link).
  // Supports both the dedicated route /detections/rules/<rule_uuid> (via the
  // initialRuleId prop) and /settings/detection?rule=<rule_uuid> (query param).
  useEffect(() => {
    const queryParam = typeof window !== "undefined" ? new URLSearchParams(window.location.search).get("rule") : null;
    const ruleParam = initialRuleId || queryParam;
    if (!ruleParam) return;
    setTopTab("rules");
    loadDetail(ruleParam).catch(() => {
      message.error("Failed to load detection rule");
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialRuleId]);

  const filteredRules = useMemo(() => {
    const query = search.trim().toLowerCase();
    return rules.filter((rule) => {
      const name = String(rule.name || rule.id || "").toLowerCase();
      const logsource = String(rule.logsource || "").toLowerCase();
      const profile = String(rule.profile || "").toLowerCase();
      const level = String(rule.level || "").toLowerCase() || "medium";
      const status = String(rule.status || "").toLowerCase() || "draft";
      const tags = (Array.isArray(rule.tags) ? rule.tags : []).join(",").toLowerCase();
      if (query && !`${rule.id} ${name} ${logsource} ${profile} ${tags}`.includes(query)) return false;
      if (productFilter !== "all" && !logsource.includes(productFilter.toLowerCase())) return false;
      if (severityFilter !== "all" && level !== severityFilter) return false;
      if (statusFilter !== "all" && status !== statusFilter) return false;
      return true;
    });
  }, [productFilter, rules, search, severityFilter, statusFilter]);

  const productOptions = useMemo(() => {
    const values = Array.from(new Set(rules.map((rule) => String(rule.logsource || "").split("/")[0].trim().toLowerCase()).filter(Boolean)));
    return [{ value: "all", label: "All Products" }, ...values.map((value) => ({ value, label: value }))];
  }, [rules]);

  const severityOptions = useMemo(() => {
    const values = Array.from(new Set(rules.map((rule) => String(rule.level || "").trim().toLowerCase()).filter(Boolean)));
    const base = ["critical", "high", "medium", "low"];
    const ordered = [...base.filter((value) => values.includes(value)), ...values.filter((value) => !base.includes(value))];
    return [{ value: "all", label: "All Severities" }, ...ordered.map((value) => ({ value, label: value }))];
  }, [rules]);

  const statusOptions = useMemo(() => {
    const values = Array.from(new Set(rules.map((rule) => String(rule.status || "").trim().toLowerCase()).filter(Boolean)));
    return [{ value: "all", label: "All Statuses" }, ...values.map((value) => ({ value, label: value }))];
  }, [rules]);

  const recordDeployment = async (payload: {
    rule_id: string;
    target: string;
    action: string;
    status: string;
    remote_id?: string;
    remote_rule_id?: string;
    message?: string;
    payload?: Record<string, any>;
  }) => {
    try {
      await createDetectionDeployment(payload);
      await loadDeployments();
    } catch {
      // Do not block the main action if audit persistence fails.
    }
  };

  const riskConfigurationPayload = () => {
    const normalizedEntities = normalizeRiskEntities(riskEntities);
    const first = normalizedEntities[0];
    if (!first) {
      return {
        entity_risk_enabled: false,
        risk_entities: [],
      };
    }
    return {
      entity_risk_enabled: true,
      alert_mode: normalizedEntities.some((entity) => entity.output === "notable") ? "notable" : "risk",
      risk_entity_type: first.entity_type,
      risk_entity_field: first.entity_field,
      risk_entities: normalizedEntities,
    };
  };

  const scheduleConfigurationPayload = () => ({
    schedule_interval: scheduleInterval,
    schedule_from: scheduleFrom,
  });

  const esqlConfigurationPayload = (source: "autogenerated" | "manual" = esqlSource) => (
    source === "manual"
      ? { esql: esqlText, esql_source: "manual" }
      : { esql_source: "autogenerated" }
  );

  const validateSchedule = () => {
    if (!/^[1-9]\d*[smhd]$/.test(scheduleInterval)) {
      throw new Error("Run every must use a value such as 1m, 5m, or 1h");
    }
    if (!/^now-[1-9]\d*[smhd]$/.test(scheduleFrom)) {
      throw new Error("Lookback must use a value such as now-16m or now-1h");
    }
  };

  const resolveCurrentElasticActions = () => {
    return routeElasticActionsByAlertMode(
      connectors,
      riskEntities,
      selectedId,
    );
  };

  const resolvedElasticActions = useMemo(() => {
    try {
      return { actions: resolveCurrentElasticActions(), error: "" };
    } catch (error: any) {
      return { actions: [], error: String(error?.message || "Unable to generate Kibana actions") };
    }
    // detail and connector changes must immediately refresh the generated preview.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [connectors, riskEntities, selectedId]);

  const buildKibanaRulePayload = () => {
    if (!selectedId || !detail) return;

    const meta = detail.meta || {};
    const compiled = detail.compiled || {};
    const compiledLanguage = String(compiled.language || (compiled.lucene ? "lucene" : "esql")).toLowerCase();
    const indexPatterns = parseIndexPatterns(elasticIndexPatternsText);
    const query =
      compiledLanguage === "lucene"
        ? String(compiled.lucene || "*")
        : applyIndexPatternsToEsql(esqlText || compiled.esql || "*", indexPatterns);
    const ruleType = compiledLanguage === "lucene" ? "query" : "esql";
    const ruleLanguage = compiledLanguage === "lucene" ? "lucene" : "esql";

    validateSchedule();
    const riskScore = Number(detail?.payload?.risk_score ?? 50);
    const actions = resolveCurrentElasticActions();
    const sigmaTags = Array.isArray(meta.tags) ? meta.tags.map((item) => String(item || "").trim()).filter(Boolean) : [];
    return {
      name: meta.title || selectedId,
      type: ruleType,
      rule_id: selectedId,
      enabled: false,
      severity: meta.level || "low",
      risk_score: Number.isFinite(riskScore) ? Math.max(0, Math.min(100, riskScore)) : 50,
      description: meta.description || meta.title || selectedId,
      index: indexPatterns,
      query,
      language: ruleLanguage,
      tags: Array.from(new Set([
        "sigma",
        ruleLanguage,
        ...(compiled.risk_incident?.enabled ? ["argus-risk-incident"] : []),
        ...riskEntities.map((entity) => `argus-output:${entity.output}`),
        ...sigmaTags,
      ])),
      actions,
      interval: scheduleInterval,
      from: scheduleFrom,
      to: "now",
    };
  };

  const buildKibanaPreviewPayload = () => {
    const payload = buildKibanaRulePayload();
    if (!payload) return;
    return {
      ...payload,
      required_fields: [],
      author: [],
      exceptions_list: [],
      false_positives: [],
      references: [],
      risk_score_mapping: [],
      severity_mapping: [],
      max_signals: 100,
      setup: "",
      license: "",
      response_actions: [],
      enabled: true,
      meta: { kibana_siem_app_url: "" },
      invocationCount: 60,
      timeframeEnd: new Date().toISOString(),
    };
  };

  const previewRule = async () => {
    if (!selectedId || !detail) return;
    setRulePreviewLoading(true);
    try {
      const payload = buildKibanaPreviewPayload();
      if (!payload) return;
      const result = await previewPublishedDetectionRule(payload);
      setRulePreviewResult(result);
      setRulePreviewOpen(true);
      message.success("Kibana rule preview completed");
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Kibana rule preview failed");
    } finally {
      setRulePreviewLoading(false);
    }
  };

  const publish = async () => {
    if (!selectedId || !detail) return;

    try {
      const payload = buildKibanaRulePayload();
      if (!payload) return;
      const actions = Array.isArray(payload.actions) ? payload.actions : [];
      const indexPatterns = Array.isArray(payload.index) ? payload.index : [];

      let publishedRule: any;
      try {
        const full = await getPublishedDetectionRule(selectedId);
        const { id: _id, rule_id: _ruleId, kibana_rule_id: _kibanaRuleId, ...fullWithoutRuleId } = full || {};
        publishedRule = await updatePublishedDetectionRule(selectedId, { ...fullWithoutRuleId, ...payload, id: selectedId });
      } catch (e: any) {
        if (e?.response?.status === 404 || e?.response?.data?.status_code === 404) {
          publishedRule = await createPublishedDetectionRule(payload);
        } else {
          throw e;
        }
      }

      const nextMetadata: KibanaMetadata = {
        published: true,
        remote_id: String(publishedRule?.kibana_rule_id || selectedId || ""),
        rule_id: String(selectedId),
        enabled: Boolean(publishedRule?.enabled ?? payload.enabled),
        name: String(publishedRule?.name || payload.name || ""),
        updated_at: new Date().toISOString(),
      };
      await saveDetectionRule(selectedId, detail.yaml || "", {
        ...riskConfigurationPayload(),
        ...scheduleConfigurationPayload(),
        ...esqlConfigurationPayload(),
        elastic_actions: actions,
        elastic_index_patterns: indexPatterns,
        kibana_metadata: nextMetadata,
      });
      setKibanaMetadata(nextMetadata);

      await recordDeployment({
        rule_id: selectedId,
        target: "elastic-dev",
        action: "publish",
        status: "success",
        remote_id: String(publishedRule?.kibana_rule_id || selectedId),
        remote_rule_id: String(publishedRule?.kibana_rule_id || selectedId),
        payload,
      });
      await loadRules();
      await loadDetail(selectedId);
      message.success("Published to Kibana");
    } catch (e: any) {
      await recordDeployment({
        rule_id: selectedId,
        target: "elastic-dev",
        action: "publish",
        status: "failed",
        message: e?.response?.data?.detail || e?.message || "Publish to Kibana failed",
      });
      message.error(e?.response?.data?.detail || e?.message || "Publish to Kibana failed");
    }
  };

  const importGithub = async () => {
    const url = githubUrl.trim();
    if (!url) return message.error("GitHub raw URL is required");
    try {
      const resp = await fetch(url);
      if (!resp.ok) throw new Error(`Fetch failed: ${resp.status}`);
      const text = await resp.text();
      const fileName = url.split("/").pop() || `import-${Date.now()}.yml`;
      const file = new File([text], fileName, { type: "text/yaml" });
      const result = await uploadDetectionRules([file]);
      const firstId = result?.results?.find((row: any) => row.id)?.id;
      await loadRules();
      if (firstId) {
        await loadDetail(String(firstId));
      }
      setTopTab("rules");
      message.success(`Imported ${fileName}`);
    } catch (e: any) {
      message.error(e?.message || "Import failed");
    }
  };

  const handleUploadFiles = async (files: File[]) => {
    if (!files.length) return;
    setUploading(true);
    try {
      const result = await uploadDetectionRules(files);
      await loadRules();
      message.success(`Upload complete: created ${result?.created || 0}, updated ${result?.updated || 0}, skipped ${result?.skipped || 0}`);
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Upload failed");
    } finally {
      setUploading(false);
    }
  };

  const deleteSelectedRules = async () => {
    if (!selectedRuleIds.length) return;
    const ids = selectedRuleIds.map((value) => String(value));
    await Promise.all(ids.map((id) => deleteDetectionRule(id)));
    if (selectedId && ids.includes(selectedId)) {
      setSelectedId("");
      setDetail(null);
    }
    setSelectedRuleIds([]);
    await loadRules();
    message.success(`Deleted ${ids.length} rules`);
  };

  const saveRule = async () => {
    if (!editorId.trim() || !editorYaml.trim()) return message.error("Rule ID and YAML are required");
    try {
      await saveDetectionRule(editorId.trim(), editorYaml, {
        ...riskConfigurationPayload(),
        ...scheduleConfigurationPayload(),
        esql_source: "autogenerated",
        elastic_actions: [],
        elastic_index_patterns: parseIndexPatterns(elasticIndexPatternsText),
        kibana_metadata: kibanaMetadata,
      });
      setEditorOpen(false);
      await loadRules();
      await loadDetail(editorId.trim());
      setEsqlSource("autogenerated");
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Failed to save rule");
    }
  };

  const saveAlertMode = async () => {
    if (!selectedId || !detail) return;
    try {
      const actions = resolveCurrentElasticActions();
      const saved = await saveDetectionRule(selectedId, detail.yaml || "", {
        ...riskConfigurationPayload(),
        ...scheduleConfigurationPayload(),
        ...esqlConfigurationPayload(),
        elastic_actions: actions,
        elastic_index_patterns: parseIndexPatterns(elasticIndexPatternsText),
        kibana_metadata: kibanaMetadata,
      });
      const savedPayload = saved?.payload && typeof saved.payload === "object" ? saved.payload : null;
      await loadDetail(selectedId);
      if (savedPayload) {
        setRiskEntities(normalizeRiskEntities(savedPayload.risk_entities));
        setScheduleInterval(String(savedPayload.schedule_interval || scheduleInterval || "1m"));
        setScheduleFrom(String(savedPayload.schedule_from || scheduleFrom || "now-16m"));
      }
      message.success("Entity risk configuration saved");
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Failed to save entity risk configuration");
    }
  };

  const saveSchedule = async () => {
    if (!selectedId || !detail) return;
    try {
      validateSchedule();
      await saveDetectionRule(selectedId, detail.yaml || "", {
        ...riskConfigurationPayload(),
        ...scheduleConfigurationPayload(),
        ...esqlConfigurationPayload(),
        elastic_actions: resolveCurrentElasticActions(),
        elastic_index_patterns: parseIndexPatterns(elasticIndexPatternsText),
        kibana_metadata: kibanaMetadata,
      });
      await loadDetail(selectedId);
      message.success("Detection schedule saved; publish to sync it to Kibana");
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Failed to save detection schedule");
    }
  };

  const saveEsql = async () => {
    if (!selectedId || !detail) return;
    if (!esqlText.trim()) {
      message.error("ES|QL query is required");
      return;
    }
    try {
      await saveDetectionRule(selectedId, detail.yaml || "", {
        ...riskConfigurationPayload(),
        ...scheduleConfigurationPayload(),
        esql: esqlText,
        esql_source: "manual",
        elastic_actions: resolveCurrentElasticActions(),
        elastic_index_patterns: parseIndexPatterns(elasticIndexPatternsText),
        kibana_metadata: kibanaMetadata,
      });
      setEsqlSource("manual");
      await loadDetail(selectedId);
      message.success("ES|QL saved as manual");
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Failed to save ES|QL");
    }
  };

  const regenerateEsqlFromSigma = async () => {
    if (!selectedId || !detail) return;
    try {
      const compiled = await compileDetectionRule(detail.yaml || "");
      const nextEsql = String(compiled?.esql || "").trim();
      if (!nextEsql) {
        throw new Error(compiled?.error || "Sigma did not compile to ES|QL");
      }
      await saveDetectionRule(selectedId, detail.yaml || "", {
        ...riskConfigurationPayload(),
        ...scheduleConfigurationPayload(),
        esql: nextEsql,
        esql_source: "autogenerated",
        elastic_actions: resolveCurrentElasticActions(),
        elastic_index_patterns: parseIndexPatterns(elasticIndexPatternsText),
        kibana_metadata: kibanaMetadata,
      });
      setEsqlText(nextEsql);
      setEsqlSource("autogenerated");
      await loadDetail(selectedId);
      message.success("ES|QL regenerated from Sigma");
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Failed to regenerate ES|QL from Sigma");
    }
  };

  const syncKibanaEnabled = async (enabled: boolean) => {
    if (!selectedId || !detail) return;
    const remoteId = String(kibanaMetadata.remote_id || "").trim();
    if (!remoteId) {
      message.error("The Kibana rule has not been published yet");
      return;
    }
    try {
      const full = await getPublishedDetectionRule(selectedId);
      const { id: _id, rule_id: _ruleId, kibana_rule_id: _kibanaRuleId, ...fullForUpdate } = full || {};
      const updated = await patchPublishedDetectionRule(selectedId, { ...fullForUpdate, enabled });
      const nextMetadata: KibanaMetadata = {
        ...kibanaMetadata,
        published: true,
        remote_id: String(updated?.kibana_rule_id || remoteId),
        rule_id: String(kibanaMetadata.rule_id || selectedId),
        enabled: Boolean(updated?.enabled),
        name: String(updated?.name || kibanaMetadata.name || detail.meta?.title || selectedId),
        updated_at: new Date().toISOString(),
      };
      await saveDetectionRule(selectedId, detail.yaml || "", {
        ...riskConfigurationPayload(),
        ...scheduleConfigurationPayload(),
        ...esqlConfigurationPayload(),
        elastic_actions: resolveCurrentElasticActions(),
        elastic_index_patterns: parseIndexPatterns(elasticIndexPatternsText),
        kibana_metadata: nextMetadata,
      });
      setKibanaMetadata(nextMetadata);
      await recordDeployment({
        rule_id: selectedId,
        target: "elastic-dev",
        action: enabled ? "enable" : "disable",
        status: "success",
        remote_id: String(updated?.kibana_rule_id || remoteId),
        remote_rule_id: String(updated?.kibana_rule_id || remoteId),
      });
      await loadRules();
      await loadDetail(selectedId);
      message.success(enabled ? "Kibana rule enabled" : "Kibana rule disabled");
    } catch (e: any) {
      await recordDeployment({
        rule_id: selectedId,
        target: "elastic-dev",
        action: enabled ? "enable" : "disable",
        status: "failed",
        message: e?.response?.data?.detail || e?.message || "Failed to update the Kibana rule",
      });
      message.error(e?.response?.data?.detail || e?.message || "Failed to update the Kibana rule");
    }
  };

  const deleteKibanaRule = async () => {
    if (!selectedId || !detail) return;
    const remoteId = String(kibanaMetadata.remote_id || "").trim();
    if (!remoteId) {
      message.error("The Kibana rule has not been published yet");
      return;
    }
    try {
      await deletePublishedDetectionRule(selectedId);
      const nextMetadata: KibanaMetadata = {
        published: false,
        remote_id: "",
        rule_id: String(kibanaMetadata.rule_id || selectedId),
        enabled: false,
        name: String(kibanaMetadata.name || detail.meta?.title || selectedId),
        updated_at: new Date().toISOString(),
      };
      await saveDetectionRule(selectedId, detail.yaml || "", {
        ...riskConfigurationPayload(),
        ...scheduleConfigurationPayload(),
        ...esqlConfigurationPayload(),
        elastic_actions: resolveCurrentElasticActions(),
        elastic_index_patterns: parseIndexPatterns(elasticIndexPatternsText),
        kibana_metadata: nextMetadata,
      });
      setKibanaMetadata(nextMetadata);
      await recordDeployment({
        rule_id: selectedId,
        target: "elastic-dev",
        action: "delete",
        status: "success",
        remote_id: remoteId,
        remote_rule_id: String(remoteId),
      });
      await loadRules();
      await loadDetail(selectedId);
      message.success("Kibana rule deleted");
    } catch (e: any) {
      await recordDeployment({
        rule_id: selectedId,
        target: "elastic-dev",
        action: "delete",
        status: "failed",
        message: e?.response?.data?.detail || e?.message || "Failed to delete the Kibana rule",
      });
      message.error(e?.response?.data?.detail || e?.message || "Failed to delete the Kibana rule");
    }
  };

  const handleUploadMappings = async (files: File[]) => {
    if (!files.length) return;
    setMappingUploading(true);
    try {
      const result = await uploadDetectionMappings(files);
      await loadMappings();
      message.success(`Mapping upload complete: created ${result?.created || 0}, updated ${result?.updated || 0}, skipped ${result?.skipped || 0}`);
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Mapping upload failed");
    } finally {
      setMappingUploading(false);
    }
  };

  const handleExportRules = async () => {
    try {
      const ids = selectedRuleIds.length ? selectedRuleIds.map((item) => String(item)) : undefined;
      const data = await exportDetectionRules(ids);
      downloadJson(`detection-rules-${new Date().toISOString().slice(0, 10)}.json`, data);
      message.success("Rules exported");
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Rule export failed");
    }
  };

  const handleExportMappings = async () => {
    try {
      const ids = selectedMappingIds.length ? selectedMappingIds.map((item) => String(item)) : undefined;
      const data = await exportDetectionMappings(ids);
      downloadBlob(`detection-mappings-${new Date().toISOString().slice(0, 10)}.csv`, data);
      message.success("Mappings exported");
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Mapping export failed");
    }
  };

  const handleDeleteMappings = async () => {
    try {
      await deleteDetectionMappings(selectedMappingIds);
      setSelectedMappingIds([]);
      await loadMappings();
      message.success("Mappings deleted");
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Delete mappings failed");
    }
  };

  const handleCreateMapping = async () => {
    try {
      await createDetectionMapping({
        ...(editingMappingId !== null ? { id: editingMappingId } : {}),
        ...mappingDraft,
        elastic_index_patterns: parseIndexPatterns(mappingDraft.elastic_index_patterns),
      });
      setMappingModalOpen(false);
      const wasEditing = editingMappingId !== null;
      setEditingMappingId(null);
      setMappingDraft({
        mapping_profile: "",
        sigma: "",
        splunk: "",
        elastic: "",
        elastic_is_multivalue: false,
        elastic_index_patterns: "",
        category: "",
        data_source: "",
        event_category: "",
      });
      await loadMappings();
      message.success(wasEditing ? "Mapping updated" : "Mapping created");
    } catch (e: any) {
      message.error(e?.response?.data?.detail || e?.message || "Create mapping failed");
    }
  };

  const handleDownloadMappingTemplate = () => {
    const lines = [
      "mapping_profile,category,data_source,event_category,sigma,splunk,elastic,elastic_is_multivalue,elastic_index_patterns",
      'aws_cloudtrail,,,,"eventName","","event.action","false","logs-aws.cloudtrail-*"',
      'aws_cloudtrail,,,,"sourceIPAddress","","source.ip","false","logs-aws.cloudtrail-*"',
    ];
    downloadText("detection-mappings-template.csv", lines.join("\n"), "text/csv;charset=utf-8");
    message.success("CSV template downloaded");
  };

  return (
    <>
      <Tabs
        activeKey={topTab}
        onChange={setTopTab}
        items={[
          {
            key: "rules",
            label: "Rule Library",
            children: selectedId && detail ? (
              <DetectionRuleDetailView
                detail={detail}
                detailTab={detailTab}
                versions={versions}
                connectors={connectors}
                resolvedElasticActionsText={formatJson(resolvedElasticActions.actions)}
                resolvedElasticActionsError={resolvedElasticActions.error}
                elasticIndexPatternsText={elasticIndexPatternsText}
                esqlText={esqlText}
                esqlSource={esqlSource}
                riskEntities={riskEntities}
                scheduleInterval={scheduleInterval}
                scheduleFrom={scheduleFrom}
                kibanaMetadata={kibanaMetadata}
                rulePreviewLoading={rulePreviewLoading}
                onBack={() => router.push(DETECTION_BASE)}
                onEdit={() => {
                  setEditorId(selectedId);
                  setEditorYaml(detail.yaml || "");
                  setEditorOpen(true);
                }}
                onPreview={previewRule}
                onPublish={publish}
                onSetDetailTab={setDetailTab}
                onRollbackVersion={async (version) => {
                  await rollbackPublishedRuleVersion(selectedId, version);
                  await loadDetail(selectedId);
                  message.success(`Rolled back to v${version}`);
                }}
                onSaveAlertMode={saveAlertMode}
                onSaveSchedule={saveSchedule}
                onSaveEsql={saveEsql}
                onRegenerateEsqlFromSigma={regenerateEsqlFromSigma}
                onSyncKibanaEnabled={syncKibanaEnabled}
                onDeleteKibanaRule={deleteKibanaRule}
                onLoadConnectors={loadConnectors}
                onSetElasticIndexPatternsText={setElasticIndexPatternsText}
                onSetEsqlText={(value) => {
                  setEsqlText(value);
                  setEsqlSource("manual");
                }}
                onSetRiskEntities={setRiskEntities}
                onSetScheduleInterval={setScheduleInterval}
                onSetScheduleFrom={setScheduleFrom}
              />
            ) : (
              <DetectionRuleList
                rules={rules}
                filteredRules={filteredRules}
                loading={loading}
                search={search}
                productFilter={productFilter}
                severityFilter={severityFilter}
                statusFilter={statusFilter}
                productOptions={productOptions}
                severityOptions={severityOptions}
                statusOptions={statusOptions}
                selectedRuleIds={selectedRuleIds}
                uploading={uploading}
                githubUrl={githubUrl}
                setSearch={setSearch}
                setProductFilter={setProductFilter}
                setSeverityFilter={setSeverityFilter}
                setStatusFilter={setStatusFilter}
                setSelectedRuleIds={setSelectedRuleIds}
                setGithubUrl={setGithubUrl}
                onReload={loadRules}
                onDeleteSelected={deleteSelectedRules}
                onSelectRule={(id) => router.push(`${DETECTION_BASE}/rules/${encodeURIComponent(String(id))}`)}
                onUploadFiles={handleUploadFiles}
                onExportRules={handleExportRules}
                onCreateRule={() => {
                  setEditorId("");
                  setEditorYaml("");
                  setElasticIndexPatternsText("logs-*");
                  setRiskEntities([]);
                  setKibanaMetadata({});
                  setEditorOpen(true);
                }}
                onImportGithub={importGithub}
              />
            ),
          },
          {
            key: "mappings",
            label: "Field Mappings",
            children: (
              <DetectionMappings
                rows={maps}
                loading={mappingUploading}
                selectedIds={selectedMappingIds}
                draft={mappingDraft}
                modalOpen={mappingModalOpen}
                onRefresh={loadMappings}
                onUpload={handleUploadMappings}
                onExport={handleExportMappings}
                onDownloadTemplate={handleDownloadMappingTemplate}
                onDeleteSelected={handleDeleteMappings}
                onOpenCreate={() => {
                  setEditingMappingId(null);
                  setMappingDraft({
                    mapping_profile: "",
                    sigma: "",
                    splunk: "",
                    elastic: "",
                    elastic_is_multivalue: false,
                    elastic_index_patterns: "",
                    category: "",
                    data_source: "",
                    event_category: "",
                  });
                  setMappingModalOpen(true);
                }}
                onOpenEdit={(row) => {
                  setEditingMappingId(row.id);
                  setMappingDraft({
                    mapping_profile: String(row.mapping_profile || ""),
                    sigma: String(row.sigma || ""),
                    splunk: String(row.splunk || ""),
                    elastic: String(row.elastic || ""),
                    elastic_is_multivalue: Boolean(row.elastic_is_multivalue),
                    elastic_index_patterns: Array.isArray(row.elastic_index_patterns) ? row.elastic_index_patterns.join("\n") : "",
                    category: String(row.category || ""),
                    data_source: String(row.data_source || ""),
                    event_category: String(row.event_category || ""),
                  });
                  setMappingModalOpen(true);
                }}
                onCloseCreate={() => {
                  setMappingModalOpen(false);
                  setEditingMappingId(null);
                }}
                onSaveCreate={handleCreateMapping}
                onSetSelectedIds={setSelectedMappingIds}
                onSetDraft={setMappingDraft}
              />
            ),
          },
          {
            key: "deployments",
            label: "Publish History",
            children: <DetectionDeployments rows={deployments} onRefresh={loadDeployments} />,
          },
        ]}
      />
      <Modal title={editorId ? `Edit Rule ${editorId}` : "New Rule"} open={editorOpen} onCancel={() => setEditorOpen(false)} onOk={saveRule} width={980}>
        <Space direction="vertical" style={{ width: "100%" }}>
          <Input placeholder="Rule ID" value={editorId} onChange={(e) => setEditorId(e.target.value)} />
          <Input.TextArea rows={18} value={editorYaml} onChange={(e) => setEditorYaml(e.target.value)} placeholder="Paste Sigma YAML" />
        </Space>
      </Modal>
      <Modal
        title="Kibana Rule Preview"
        open={rulePreviewOpen}
        onCancel={() => setRulePreviewOpen(false)}
        footer={<Button onClick={() => setRulePreviewOpen(false)}>Close</Button>}
        width={980}
      >
        <Space direction="vertical" style={{ width: "100%" }} size={12}>
          <Card size="small">
            <Space wrap size={24}>
              <Statistic
                title="Matched events"
                value={rulePreviewResult?.alert_summary?.count ?? "Unknown"}
              />
              <Statistic
                title="Executions"
                value={Array.isArray(rulePreviewResult?.logs) ? rulePreviewResult.logs.length : 0}
              />
              <Statistic
                title="Preview ID"
                value={rulePreviewResult?.previewId || "-"}
                valueStyle={{ fontSize: 14 }}
              />
            </Space>
            {rulePreviewResult?.alert_summary?.ok === false ? (
              <Typography.Paragraph type="warning" style={{ marginTop: 12, marginBottom: 0 }}>
                Preview ran, but match count could not be loaded from Elasticsearch: {String(rulePreviewResult?.alert_summary?.error || "unknown error")}
              </Typography.Paragraph>
            ) : null}
            {rulePreviewResult?.alert_summary?.ok === true && rulePreviewResult?.alert_summary?.count === 0 ? (
              <Typography.Paragraph type="secondary" style={{ marginTop: 12, marginBottom: 0 }}>
                No preview alerts matched the current preview id yet. Check the JSON below for queried indices and sample alerts.
              </Typography.Paragraph>
            ) : null}
          </Card>
          <Table
            size="small"
            rowKey={(row: any) => String(row.id || row.source?.["kibana.alert.uuid"] || row.source?.["@timestamp"] || Math.random())}
            dataSource={Array.isArray(rulePreviewResult?.alert_summary?.alerts) ? rulePreviewResult.alert_summary.alerts : []}
            pagination={false}
            scroll={{ x: 900 }}
            columns={[
              {
                title: "Time",
                dataIndex: ["source", "@timestamp"],
                width: 210,
                render: (value: any, row: any) => String(value || row.source?.["kibana.alert.start"] || "-"),
              },
              {
                title: "Index",
                dataIndex: "index",
                width: 280,
                render: (value: any) => String(value || "-"),
              },
              {
                title: "Host",
                dataIndex: ["source", "host.name"],
                width: 220,
                render: (value: any, row: any) => String(value || row.source?.host?.name || row.source?.host?.hostname || "-"),
              },
              {
                title: "User",
                dataIndex: ["source", "user.name"],
                width: 160,
                render: (value: any, row: any) => String(value || row.source?.user?.name || row.source?.user?.id || "-"),
              },
              {
                title: "Process",
                dataIndex: ["source", "process.executable"],
                width: 260,
                render: (value: any, row: any) => String(value || row.source?.process?.executable || row.source?.process?.name || "-"),
              },
              {
                title: "Reason",
                dataIndex: ["source", "kibana.alert.reason"],
                render: (value: any) => String(value || "-"),
              },
            ]}
          />
          <Collapse
            size="small"
            items={[
              {
                key: "raw",
                label: "Raw preview response",
                children: (
                  <Input.TextArea
                    value={formatJson(rulePreviewResult)}
                    readOnly
                    rows={14}
                    style={{ fontFamily: "Consolas, 'Courier New', monospace" }}
                  />
                ),
              },
            ]}
          />
        </Space>
      </Modal>
    </>
  );
}
