import re

from rest_framework import serializers

from .models import LocalDetectionDeployment, LocalDetectionFieldMapping


class RiskEntitySerializer(serializers.Serializer):
    entity_type = serializers.ChoiceField(choices=("host", "user", "ip", "service", "risk_object"))
    entity_field = serializers.CharField(allow_blank=False)
    risk_score = serializers.IntegerField(min_value=0, max_value=100)
    output = serializers.ChoiceField(choices=("risk", "notable"))

    def validate_entity_field(self, value):
        if not re.fullmatch(r"[A-Za-z0-9_.-]+", str(value)):
            raise serializers.ValidationError("Use a valid ECS-style field path.")
        return value

class DetectionRuleSaveSerializer(serializers.Serializer):
    yaml = serializers.CharField(required=True, allow_blank=False)
    esql = serializers.CharField(required=False, allow_blank=True)
    esql_source = serializers.ChoiceField(
        choices=("autogenerated", "manual"),
        required=False,
    )
    schedule_interval = serializers.RegexField(r"^[1-9]\d*[smhd]$", required=False)
    schedule_from = serializers.RegexField(r"^now-[1-9]\d*[smhd]$", required=False)
    entity_risk_enabled = serializers.BooleanField(required=False)
    alert_mode = serializers.ChoiceField(
        choices=("notable", "risk"),
        required=False,
    )
    risk_entity_type = serializers.ChoiceField(
        choices=("host", "user", "ip", "service", "risk_object"),
        required=False,
    )
    risk_entity_field = serializers.CharField(required=False, allow_blank=False)
    risk_entities = RiskEntitySerializer(many=True, required=False, allow_empty=True)
    elastic_actions = serializers.ListField(required=False)
    elastic_index_patterns = serializers.ListField(
        child=serializers.CharField(allow_blank=False),
        required=False,
    )
    kibana_metadata = serializers.DictField(required=False)

    def validate(self, attrs):
        entity_field = str(attrs.get("risk_entity_field") or "")
        if entity_field and not re.fullmatch(r"[A-Za-z0-9_.-]+", entity_field):
            raise serializers.ValidationError({"risk_entity_field": "Use a valid ECS-style field path."})
        if attrs.get("entity_risk_enabled") and not attrs.get("risk_entities"):
            raise serializers.ValidationError({"risk_entities": "At least one entity is required when Entity Risk is enabled."})
        return attrs


class DetectionRuleCompileSerializer(serializers.Serializer):
    yaml = serializers.CharField(required=True, allow_blank=False)


class DetectionMappingSerializer(serializers.ModelSerializer):
    sigma = serializers.CharField(source="sigma_field")
    splunk = serializers.CharField(source="splunk_field")
    elastic = serializers.CharField(source="elastic_field")
    elastic_index_patterns = serializers.ListField(child=serializers.CharField(), read_only=True)

    class Meta:
        model = LocalDetectionFieldMapping
        fields = (
            "id",
            "category",
            "data_source",
            "event_category",
            "mapping_profile",
            "sigma",
            "splunk",
            "elastic",
            "elastic_is_multivalue",
            "elastic_index_patterns",
        )


class DetectionMappingSaveSerializer(serializers.Serializer):
    id = serializers.IntegerField(required=False)
    mapping_profile = serializers.CharField(required=True, allow_blank=False)
    sigma = serializers.CharField(required=True, allow_blank=False)
    splunk = serializers.CharField(required=False, allow_blank=True, default="")
    elastic = serializers.CharField(required=False, allow_blank=True, default="")
    elastic_is_multivalue = serializers.BooleanField(required=False, default=False)
    elastic_index_patterns = serializers.ListField(
        child=serializers.CharField(allow_blank=False),
        required=False,
        default=list,
    )
    category = serializers.CharField(required=False, allow_blank=True, default="")
    data_source = serializers.CharField(required=False, allow_blank=True, default="")
    event_category = serializers.CharField(required=False, allow_blank=True, default="")


class DetectionMappingDeleteSerializer(serializers.Serializer):
    ids = serializers.ListField(child=serializers.CharField(allow_blank=False), required=True, allow_empty=False)


class DetectionDeploymentSerializer(serializers.ModelSerializer):
    id = serializers.UUIDField(source="deployment_uuid", read_only=True)
    rule_id = serializers.CharField(source="rule.rule_uuid", read_only=True)

    class Meta:
        model = LocalDetectionDeployment
        fields = (
            "id",
            "rule_id",
            "rule_name",
            "target",
            "action",
            "status",
            "remote_id",
            "remote_rule_id",
            "message",
            "payload",
            "created_by",
            "created_at",
        )


class DetectionDeploymentCreateSerializer(serializers.Serializer):
    rule_id = serializers.CharField(required=True, allow_blank=False)
    target = serializers.CharField(required=True, allow_blank=False)
    action = serializers.CharField(required=True, allow_blank=False)
    status = serializers.CharField(required=True, allow_blank=False)
    remote_id = serializers.CharField(required=False, allow_blank=True)
    remote_rule_id = serializers.CharField(required=False, allow_blank=True)
    message = serializers.CharField(required=False, allow_blank=True)
    payload = serializers.JSONField(required=False)


class KibanaPublishedRuleListQuerySerializer(serializers.Serializer):
    page = serializers.IntegerField(required=False, min_value=1, default=1)
    per_page = serializers.IntegerField(required=False, min_value=1, max_value=10000, default=20)
    filter = serializers.CharField(required=False, allow_blank=True, default="")
    sort_field = serializers.CharField(required=False, allow_blank=True, default="updated_at")
    sort_order = serializers.ChoiceField(required=False, choices=["asc", "desc"], default="desc")


class KibanaRollbackSerializer(serializers.Serializer):
    version = serializers.IntegerField(required=True, min_value=1)
