# Generated by Django 6.0.2 on 2026-04-09 02:34

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('window_minutes', models.IntegerField(default=30)),
                ('match_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list)),
                ('match_risk_object', models.BooleanField(default=True)),
                ('match_detection_rule', models.BooleanField(default=True)),
                ('match_source_ip', models.BooleanField(default=False)),
                ('match_username', models.BooleanField(default=False)),
                ('time_window_hours', models.IntegerField(default=8)),
                ('match_action', models.CharField(default='attach', max_length=32)),
                ('rules_expression', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrelationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('alert_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list)),
                ('threat_object', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('matched_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['occurred_at'], name='correlation_occurre_d568c2_idx'), models.Index(fields=['threat_object', 'occurred_at'], name='correlation_threat__77e880_idx')],
            },
        ),
    ]
